AllCops:
  Includes:
    - lib/*.rb
    - modules/*.rb
  Excludes:
    - Gemfile
Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: true
  Max: 17.5

Metrics/LineLength:
  Enabled: true
  Max: 100

Metrics/MethodLength:
  CountComments: false
  Max: 15